### ISSUE TITLE
Unable to Translate

### ISSUE THREAD

**Issue by bd0n4lds** [bd0n4lds/Verfasser#1]
C:\Users\bd90809\Documents\GitHub\Verfasser>python verfasser.py 'hallo' -s nl -d en
Traceback (most recent call last):
  File "verfasser.py", line 47, in <module>
    print(translate(target, src=src, dest=dest))
  File "verfasser.py", line 11, in translate
    return translator.translate(text, src=src, dest=dest).text
  File "C:\Users\bd90809\AppData\Local\Programs\Python\Python38\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "C:\Users\bd90809\AppData\Local\Programs\Python\Python38\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\bd90809\AppData\Local\Programs\Python\Python38\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "C:\Users\bd90809\AppData\Local\Programs\Python\Python38\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group

**Comment by bd0n4lds** [comment]
Found work around.
